### ISSUE TITLE
do you accept patches for networking or hypervisor?

### ISSUE THREAD

**Issue by chillancezen** [qword-os/qword#30]

**Comment by chillancezen** [comment]
hi I am interested in networking and virtualization, wish I could contribute to this beautiful OS/Kernel.

**Comment by avdgrinten** [comment]
Yes. We accept patches in all areas if they are of high quality and respect the license.

**Comment by chillancezen** [comment]
> Yes. We accept patches in all areas if they are of high quality and respect the license.

that's great~

**Comment by too-r** [comment]
Make sure you follow the conventions laid out by the rest of the code in the kernel
