### ISSUE TITLE
could QwordOS fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [qword-os/qword#33]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

@mintsuki and @too-r , If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by carverh** [comment]
You already asked this question

**Comment by informer2016** [comment]
@carverh Sorry, for some reason I can't see it in issues and forgot what was a previous answer

**Comment by carverh** [comment]
> @carverh Sorry, for some reason I can't see it in issues and forgot what was a previous answer

The answer was "go away and stop asking for people to fit their operating systems within 1.44MB"

**Comment by informer2016** [comment]
@carverh why "1.44MB" ? 2.88MB is also supported, although this is a rare type of a floppy :wink: If even FreeDOS could fit there fine, why Qword couldn't ? Also, it's a bit weird that a prebuilt downloadable Qword [weights 4GB](https://ci.oogacraft.com/job/qword/lastSuccessfulBuild/artifact/qword.hdd), more than any Linux distro. Maybe some optimizations could be made?

**Comment by avdgrinten** [comment]
That's because of debugging symbols. Qword also includes much more than a typical DOS-era OS. In particular, GCC alone is more than 2.88MB even if you strip it. GCC's backend for C++,  `cc1plus`, is 23 MiB on my Linux system.

In the end, nobody stops you from trying to fit Qword onto a floppy but it's a huge amount of work (porting smaller replacements for tools like coreutils) with no real benefit for the core developers.

**Comment by informer2016** [comment]
@avdgrinten Thank you very much for your detailed reply. By the way, it seems that a lot of issues have been lost without a trace - the earliest I could find is @carverh 's  [#17 Rename to "n-word"](https://github.com/qword-os/qword/issues/17)
