### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by NikolaTesla13** [qword-os/qword#44]
I'm using Ubuntu.
I enable Virtualization on my machine.
Here is the terminal output:
```
$ qemu-system-x86_64 -enable-kvm -cpu host -smp 4 -m 2G -hda qword.hdd
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize KVM: No such file or directory
```
How can I solve it?

**Comment by jlagarespo** [comment]
Are you running this inside a virtual machine?
* If you are I honestly don't know how you would enable virtualization inside an already virtualized machine. I don't think it's even possible (KVM virtualization would make much sense anyways, as it would be virtualized in software anyway). Just remove the -enable-kvm option.
* If you are not, then make sure KVM is enabled from the BIOS.

**Comment by NikolaTesla13** [comment]
Now it gives me a different error:
```
$ qemu-system-x86_64 -cpu host -smp 4 -m 2G -hda qword.hdd
WARNING: Image format was not specified for 'qword.hdd' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu-system-x86_64: CPU model 'host' requires KVM
```
I'm using Ubuntu WSL 19.04

**Comment by Itay2805** [comment]
WSL does *NOT* support KVM, you will need to remove the `-enable-kvm`

**Comment by NikolaTesla13** [comment]
I've already remove it, look at the previous post.

**Comment by qookei** [comment]
The error is pretty clear, you need to remove the `-cpu host` argument since that requires KVM

**Comment by jlagarespo** [comment]
Oh, I have no experience with WSL. As @qookei said, if you want to use your host CPU for virtualization then you are forced to enable KVM.

**Comment by NikolaTesla13** [comment]
Another error:
```

$ qemu-system-x86_64  -smp 4 -m 2G -hda qword.hdd
WARNING: Image format was not specified for 'qword.hdd' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
Could not initialize SDL(No available video device) - exiting

```

**Comment by NikolaTesla13** [comment]
Now, I've tried to run on CMD instead of WSL. Now it works, but I have a problem with the os.
![qemuimg](https://user-images.githubusercontent.com/52822996/73603641-3f6cf800-458e-11ea-9bd4-62eb6c4444b9.png)

**Comment by jlagarespo** [comment]
You have not specified a root partition in the kernel boot options. If you are using grub to bootload then specify said argument there. Or optionally you can just provide it with the root partition on the prompt qemu itself gives you.
