### ISSUE TITLE
Install package

### ISSUE THREAD

**Issue by NikolaTesla13** [qword-os/qword#45]
How can I install packages on Qword?
I've tried the following commands:
```
apt
yum
zypper
pacman
```
What kind of distro is Qword?

**Comment by Itay2805** [comment]
Qword is not a distro, it is a kernel/operating system made from scratch. Currently there is no package manager but it will be added once the network stack is ready (hopefully in the next few weeks).

**Comment by NikolaTesla13** [comment]
Then... how does it have already have installed g++/gcc?

**Comment by Itay2805** [comment]
We manually port and build everything which comes pre installed.

**Comment by avdgrinten** [comment]
See the `bootstrap.yml` file which determines how all package are built and installed.
