### ISSUE TITLE
real mode->long mode jump in smp trampoline and real mode drops may cause problems on some cpus due to intel giving themselves wiggling room

### ISSUE THREAD

**Issue by Menotdan** [qword-os/qword#49]
In the SMP trampoline code and in places where qword drops to or returns from real mode, there is a problematic mode switch directly from real mode to long mode which goes against the Intel IA-32 SDM. No cases to cause an issue with this have been discovered, but to comply with the spec it might be a good idea to change it.

**Comment by streaksu** [comment]
While I understand this can in a theoretical level be an issue, no issues have been ever discovered by any of our testers on machines from a lot of x86 desktop vendors.

Won't fix, for now.
