### ISSUE TITLE
Can I use the code in this OS on my Cadex OS?

### ISSUE THREAD

**Issue by asiawin** [qword-os/qword#57]
I have a question. Can I use the code in this OS in my [CadexOS](http://github.com/OpenCreeck/Cadex-OS-Official)? It's licensed under GPLv2.

**Comment by franeklubi** [comment]
**I THINK && THIS IS NOT A LEGAL ADVICE**

If You want to use the code in this repository in Yours, You need to include the verbatim copyright notice found in [LICENSE](LICENSE), marking that the code comes from this project and that the code in these files is not under the GPLv2 that Your repository is using.

**Comment by asiawin** [comment]
Ok. I now thought **NOT** to use the code in Qword OS because my OS is 32 bit.
